Document: docker-compose-bin
Title: Debian docker-compose-bin Manual
Author: <insert document author here>
Abstract: This manual describes what docker-compose-bin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/docker-compose-bin/docker-compose-bin.sgml.gz

Format: postscript
Files: /usr/share/doc/docker-compose-bin/docker-compose-bin.ps.gz

Format: text
Files: /usr/share/doc/docker-compose-bin/docker-compose-bin.text.gz

Format: HTML
Index: /usr/share/doc/docker-compose-bin/html/index.html
Files: /usr/share/doc/docker-compose-bin/html/*.html
